version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: pg_local
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: welllogs
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  cassandra:
    image: cassandra:4.1
    container_name: cassandra_local
    environment:
      CASSANDRA_CLUSTER_NAME: "LocalCluster"
      CASSANDRA_NUM_TOKENS: 8
      CASSANDRA_START_RPC: "true"
    ports:
      - "9042:9042"   # CQL port
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  pg_data:
  cassandra_data:
